### ISSUE TITLE
admin/config/ethereum/network HTTP 500 Error

### ISSUE THREAD

**Issue by jeffanthony** [digitaldonkey/ethereum#2]
no page shows when I try to assign my network URL

**Comment by digitaldonkey** [comment]
Please provide more precise information.

**Comment by jeffanthony** [comment]
probably due to my weakness with php/composer, but once Drupal seems to work completely I get a 500 error at website.com/admin/config/ethereum/network which appears upon clicking the 'submit' button after assigning my network url

**Comment by jeffanthony** [comment]
okay this has been fixed, I added 'composer install'  at the right spot
