### ISSUE TITLE
Unable to verify user account

### ISSUE THREAD

**Issue by patilmahesh0008** [digitaldonkey/ethereum#24]
Hi Team,

I am trying to verify the "user" but status is not getting updated in Drupal Database. I am using Koven Network transaction are submitted successfully and block size also get increased only problem in Drupal 
ValidateEthereumAccount.php in public function get($hash)  function. Something problem in argument passing $eth = new EthereumUserConnectorController();

Please see below error for more details.

ArgumentCountError: Too few arguments to function Drupal\ethereum_user_connector\Plugin\rest\resource\ValidateEthereumAccount::__construct(), 6 passed in /opt/lampp/htdocs/drupal/web/modules/contrib/ethereum/ethereum_user_connector/src/Plugin/rest/resource/ValidateEthereumAccount.php on line 85 and exactly 7 expected in Drupal\ethereum_user_connector\Plugin\rest\resource\ValidateEthereumAccount->__construct() (line 62 of /opt/lampp/htdocs/drupal/web/modules/contrib/ethereum/ethereum_user_connector/src/Plugin/rest/resource/ValidateEthereumAccount.php) #0 /opt/lampp/htdocs/drupal/web/modules/contrib/ethereum/ethereum_user_connector/src/Plugin/rest/resource/ValidateEthereumAccount.php(85): Drupal\ethereum_user_connector\Plugin\rest\resource\ValidateEthereumAccount->__construct(Array, 'validate_ethere...', Array, Array, Object(Drupal\Core\Logger\LoggerChannel), Object(Drupal\Core\Session\AccountProxy)) #1 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Core/Plugin/Factory/ContainerFactory.php(21): Drupal\ethereum_user_connector\Plugin\rest\resource\ValidateEthereumAccount::create(Object(Drupal\Core\DependencyInjection\Container), Array, 'validate_ethere...', Array) #2 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Component/Plugin/PluginManagerBase.php(84): Drupal\Core\Plugin\Factory\ContainerFactory->createInstance('validate_ethere...', Array) #3 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Core/Plugin/DefaultSingleLazyPluginCollection.php(62): Drupal\Component\Plugin\PluginManagerBase->createInstance('validate_ethere...', Array) #4 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Component/Plugin/LazyPluginCollection.php(80): Drupal\Core\Plugin\DefaultSingleLazyPluginCollection->initializePlugin('validate_ethere...') #5 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Core/Plugin/DefaultSingleLazyPluginCollection.php(83): Drupal\Component\Plugin\LazyPluginCollection->get('validate_ethere...') #6 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Core/Plugin/DefaultSingleLazyPluginCollection.php(99): Drupal\Core\Plugin\DefaultSingleLazyPluginCollection->setConfiguration(Array) #7 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Core/Plugin/DefaultSingleLazyPluginCollection.php(55): Drupal\Core\Plugin\DefaultSingleLazyPluginCollection->addInstanceId('validate_ethere...', Array) #8 /opt/lampp/htdocs/drupal/web/core/modules/rest/src/Entity/RestResourceConfig.php(206): Drupal\Core\Plugin\DefaultSingleLazyPluginCollection->__construct(Object(Drupal\rest\Plugin\Type\ResourcePluginManager), 'validate_ethere...', Array) #9 /opt/lampp/htdocs/drupal/web/core/modules/rest/src/Entity/RestResourceConfig.php(111): Drupal\rest\Entity\RestResourceConfig->getPluginCollections() #10 /opt/lampp/htdocs/drupal/web/core/modules/rest/src/RequestHandler.php(78): Drupal\rest\Entity\RestResourceConfig->getResourcePlugin() #11 [internal function]: Drupal\rest\RequestHandler->handle(Object(Drupal\Core\Routing\RouteMatch), Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\rest\Entity\RestResourceConfig)) #12 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #13 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #14 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #15 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #16 /opt/lampp/htdocs/drupal/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #17 /opt/lampp/htdocs/drupal/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #18 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #19 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /opt/lampp/htdocs/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /opt/lampp/htdocs/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(50): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /opt/lampp/htdocs/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #25 /opt/lampp/htdocs/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(664): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #26 /opt/lampp/htdocs/drupal/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #27 {main}.

**Comment by digitaldonkey** [comment]
I just pushed pushed a (actually "the") mayor update to the 8.x-1.x branch. 
Can you retest please.
