### ISSUE TITLE
admin/config/ethereum/smartcontract/register_drupal

### ISSUE THREAD

**Issue by jeffanthony** [digitaldonkey/ethereum#48]
Upon page-load 1) **even though the contract_src is not modified the ABI appears to be generated** unnecessarily. Additionally, I seem to be 2) **forced to modify contract_src in order for the 'Save' button to activate**. This complicates attempting to modify the contract address for a given network as it is 3) **not intuitive to make a change to the contract_src essentially appearing to be a broken Save button**.

Kudos! to great work overall. I think it is great an ABI can be generated on the fly or through truffle via the interface but I'd appreciate the freedom to paste in my own ABI and not expose the contract for some cases. Regardless, the Solidity is not an essential component to Drupal so its importance should be downplayed here in my opinion, UNLESS...; the roadmap includes ability to compile and deploy smart contracts to the selected network and populate the form's address field with the newly generated contract's address.

**Comment by digitaldonkey** [comment]
I agree with you. That is currently pretty shitty. My goal was to minimize the extra tooling required to use a contract. 
My secret goal was to implement remix browser IDE somehow, but that's a huge task and a fast moving target. 

We might just change the fields to include the ABI and drop the silly Solidity compiler stuff (which is most probably outdated again anyway....)

My Idea was to use different "field plugins" (was it that..?) for different use cases. I think for any more serious setup you would want to use truffle import as it would saved in code and only imported in config.
