### ISSUE TITLE
Quick issue on colon in ethereum_address_field.info.yml

### ISSUE THREAD

**Issue by jdidelet** [digitaldonkey/ethereum#7]
The installation is currently generating error because we have (:) in description within ethereum_address_field.info.yml.

**Comment by digitaldonkey** [comment]
Thanks. Fixed in https://github.com/digitaldonkey/ethereum/commit/84f072d491ebd24c64b5e98717e9589175a753de

**Comment by jdidelet** [comment]
Thanks!
