### ISSUE TITLE
Fatal error: Class 'Drupal\options\Plugin\Field\FieldType\ListStringItem' not found in {ROOT_PATH}/modules/contrib/ethereum/ethereum_user_connector/src/Plugin/Field/FieldType/EthereumStatus.php on line 25

### ISSUE THREAD

**Issue by jdidelet** [digitaldonkey/ethereum#8]
Hi,

I have this error when:
- First time I enable the module ethereum_user_connector
- When I go to /admin/config/people/accounts/fields/add-field

Thanks!

**Comment by digitaldonkey** [comment]
This should be solved by now.
